<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="OCT-JULIEN" failures="1" tests="19" name="Default test" time="70.275" errors="0" timestamp="2022-07-20T16:05:10 WAT">
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField1" time="5.294"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField2" time="3.639"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField3" time="3.38"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField4" time="3.178"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField5" time="3.707"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField6" time="3.239"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateEmailField7" time="3.197"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePhonenumberField1" time="3.167"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePhonenumberField2" time="3.112"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePhonenumberField3" time="3.142"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePasswordField1" time="3.142"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePasswordField2" time="3.166"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePasswordField3" time="3.04"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePasswordField4" time="2.976"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidatePasswordField5" time="2.998"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateConfirmpasswordField" time="3.323"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateDuplicateUsercreation" time="2.997"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateRequiredFields" time="0.217"/>
  <testcase classname="alphaTests.SignUpTest" name="ValidateValidInputsWithValidDataFormat" time="3.067">
    <failure type="java.lang.AssertionError" message="expected [https://alphapay.netlify.app/dashboard/overview] but found [https://alphapay.netlify.app/auth/signup]">
      <![CDATA[java.lang.AssertionError: expected [https://alphapay.netlify.app/dashboard/overview] but found [https://alphapay.netlify.app/auth/signup]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at alphaTests.SignUpTest.ValidateValidInputsWithValidDataFormat(SignUpTest.java:168)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateValidInputsWithValidDataFormat -->
</testsuite> <!-- Default test -->
